version: '3'

services:
  web:
    build: .
    command: bash -c "ls && cd todo_project && ls && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todo_app
    volumes:
      - .:/todo_app
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
