# Generated by Django 3.1.4 on 2021-01-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20210103_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete_at',
            field=models.DateTimeField(default=None),
        ),
    ]
