# Generated by Django 3.1.4 on 2021-01-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_blacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
