# Generated by Django 3.1.4 on 2021-01-03 03:46

from django.db import migrations, models
import todo_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todo_complete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=todo_app.utils.date_shift),
        ),
    ]
